---
# defaults file for provision_esxi

mirror_base: '/opt/openshift'

run_as_root: false
pip_args: ''
pip_cmd: /usr/local/bin/pip3

vmware_ssl_enabled: false

vcenter_username: ''
vcenter_password: ''
vcenter_hostname: ''
datacenter_name: 'ha-datacenter'
datastore_name: 'NVMe-Datastore'
datastore_path: 'ISOs/RHCOS'
vswitch_name: ''
portgroup_name: ''
vcenter_cluster_name: ''
upload_ova: false
arch: 'x86_64'
rhcos_ver: '4.3.8'
